version: "3.5"
services:
  app_auth_oauth:
    build: .
    image: 'app_auth_oauth:1'
    container_name: 'app_auth_oauth'
    command: >
      sh -c "cd src &&
             python3 manage.py migrate --no-input &&
             python3 manage.py createadmin &&
             python3 manage.py runserver_plus 0.0.0.0:8080 --cert-file cert.crt"
    networks:
      - backend
    ports:
      - '8080:8080'
    env_file: ./.env.example
    volumes:
      - ./src:/service/src
    restart: unless-stopped
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:13
    container_name: 'db_postgres'
    networks:
      - backend
    env_file: ./.env.example
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
networks:
  backend:
    driver: bridge
volumes:
  postgres: