# Generated by Django 4.2.3 on 2023-08-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='verbose',
            new_name='verb',
        ),
    ]
