# Generated by Django 4.2.3 on 2023-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='image_image_created_f4c9e6_idx'),
        ),
    ]
