# Generated by Django 4.2.3 on 2023-08-02 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0002_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
